# Generated by Django 4.2.7 on 2026-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de permisos asignados al rol'),
        ),
    ]
