# Generated by Django 4.2.7 on 2026-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muertebaja',
            name='tipo',
            field=models.CharField(choices=[('MUERTE', 'Muerte'), ('ROBO', 'Robo'), ('SACRIFICIO', 'Sacrificio'), ('DESCARTE', 'Descarte'), ('PERDIDA', 'Pérdida'), ('OTRO', 'Otro')], max_length=30),
        ),
    ]
