# Generated by Django 6.0.4 on 2026-04-25 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('fincas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACUNA_PROXIMA', 'Vacuna próxima'), ('VACUNA_VENCIDA', 'Vacuna vencida'), ('PARTO_PROXIMO', 'Parto próximo'), ('STOCK_BAJO_MEDICAMENTO', 'Stock bajo de medicamento'), ('STOCK_BAJO_ALIMENTO', 'Stock bajo de alimento'), ('PESAJE_PENDIENTE', 'Pesaje pendiente'), ('OTRO', 'Otro')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_alerta', models.DateField()),
                ('dias_restantes', models.IntegerField(default=0)),
                ('leida', models.BooleanField(default=False)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_gasto', models.CharField(choices=[('SANIDAD', 'Sanidad'), ('REPRODUCCION', 'Reproducción'), ('ALIMENTO', 'Alimento'), ('MANO_DE_OBRA', 'Mano de obra'), ('TRANSPORTE', 'Transporte'), ('MANTENIMIENTO', 'Mantenimiento'), ('COMBUSTIBLE', 'Combustible'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
