# Generated by Django 6.0.4 on 2026-04-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orientacion', models.CharField(choices=[('CARNE', 'Carne'), ('LECHE', 'Leche'), ('DOBLE_PROPOSITO', 'Doble propósito')], default='DOBLE_PROPOSITO', max_length=30)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('contenido_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='fincas.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=150, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contenido_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intervalo_dias', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='medicamentos/')),
                ('activo', models.BooleanField(default=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='fincas.finca')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tipomedicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.CharField(blank=True, max_length=30, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarios', to='fincas.finca')),
            ],
        ),
    ]
