# Generated by Django 6.0.4 on 2026-04-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_origen', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('SEMEN', 'Semen')], max_length=30)),
                ('codigo_pajuela', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductores', to='fincas.finca')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproductores', to='catalogos.raza')),
            ],
        ),
    ]
