# Generated by Django 4.2.7 on 2026-04-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
        ('catalogos', '0002_reproductor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='categoriaanimal',
            options={'verbose_name': 'Categoría Animal', 'verbose_name_plural': 'Categorías Animales'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'verbose_name': 'Raza', 'verbose_name_plural': 'Razas'},
        ),
        migrations.AlterModelOptions(
            name='reproductor',
            options={'verbose_name': 'Reproductor', 'verbose_name_plural': 'Reproductores'},
        ),
        migrations.AlterModelOptions(
            name='tipomedicamento',
            options={'verbose_name': 'Tipo de Medicamento', 'verbose_name_plural': 'Tipos de Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'verbose_name': 'Veterinario', 'verbose_name_plural': 'Veterinarios'},
        ),
        migrations.AlterModelTable(
            name='alimento',
            table='catalogos_alimento',
        ),
        migrations.AlterModelTable(
            name='categoriaanimal',
            table='catalogos_categoria_animal',
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='catalogos_medicamento',
        ),
        migrations.AlterModelTable(
            name='raza',
            table='catalogos_raza',
        ),
        migrations.AlterModelTable(
            name='reproductor',
            table='catalogos_reproductor',
        ),
        migrations.AlterModelTable(
            name='tipomedicamento',
            table='catalogos_tipo_medicamento',
        ),
        migrations.AlterModelTable(
            name='veterinario',
            table='catalogos_veterinario',
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dosis_recomendada', models.CharField(help_text='Ej: 2 ml', max_length=50)),
                ('via_aplicacion', models.CharField(choices=[('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutánea'), ('INTRADERMICA', 'Intradérmica'), ('ORAL', 'Oral')], default='INTRAMUSCULAR', max_length=20)),
                ('intervalo_dias', models.IntegerField(default=365, help_text='Días entre dosis (refuerzo)')),
                ('edad_minima_meses', models.IntegerField(default=0, help_text='Edad mínima en meses para aplicar')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'db_table': 'catalogos_vacuna',
                'ordering': ['nombre'],
            },
        ),
    ]
