# Generated by Django 4.2.7 on 2026-04-26 17:43
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
        ('catalogos', '0003_alter_alimento_options_alter_categoriaanimal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fincas', '0001_initial'),
        ('sanidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalmedicamento',
            options={'verbose_name': 'Animal Medicamento', 'verbose_name_plural': 'Animales Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='desparasitacion',
            options={'verbose_name': 'Desparasitación', 'verbose_name_plural': 'Desparasitaciones'},
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'ordering': ['-fecha'], 'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Observación', 'verbose_name_plural': 'Observaciones'},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AlterModelOptions(
            name='tratamientomedicamento',
            options={'verbose_name': 'Tratamiento Medicamento', 'verbose_name_plural': 'Tratamientos Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='vacunacion',
            options={'ordering': ['-fecha_aplicacion'], 'verbose_name': 'Vacunación', 'verbose_name_plural': 'Vacunaciones'},
        ),
        migrations.RenameField(
            model_name='vacunacion',
            old_name='fecha',
            new_name='fecha_aplicacion',
        ),
        migrations.RemoveField(
            model_name='vacunacion',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='vacunacion',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='vacunacion',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='vacunacion',
            name='proxima_fecha',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='dosis_aplicada',
            field=models.CharField(blank=True, help_text='Dosis realmente aplicada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='vacuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vacunaciones', to='catalogos.vacuna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='animales.animal'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='campana',
            field=models.CharField(blank=True, help_text='Campaña de vacunación', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='fecha_proxima',
            field=models.DateField(blank=True, help_text='Fecha de próxima dosis (refuerzo)', null=True),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='fincas.finca'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones_realizadas', to='catalogos.veterinario'),
        ),
        migrations.AlterUniqueTogether(
            name='animalmedicamento',
            unique_together={('animal', 'medicamento', 'fecha_administracion')},
        ),
        migrations.AlterUniqueTogether(
            name='tratamientomedicamento',
            unique_together={('tratamiento', 'medicamento')},
        ),
        migrations.AlterModelTable(
            name='animalmedicamento',
            table='sanidad_animal_medicamento',
        ),
        migrations.AlterModelTable(
            name='desparasitacion',
            table='sanidad_desparasitacion',
        ),
        migrations.AlterModelTable(
            name='diagnostico',
            table='sanidad_diagnostico',
        ),
        migrations.AlterModelTable(
            name='observacion',
            table='sanidad_observacion',
        ),
        migrations.AlterModelTable(
            name='tratamiento',
            table='sanidad_tratamiento',
        ),
        migrations.AlterModelTable(
            name='tratamientomedicamento',
            table='sanidad_tratamiento_medicamento',
        ),
        migrations.AlterModelTable(
            name='vacunacion',
            table='sanidad_vacunacion',
        ),
    ]