# Generated by Django 4.2.7 on 2026-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_alter_animalmedicamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desparasitacion',
            name='producto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
