# Generated by Django 6.0.4 on 2026-04-25 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('catalogos', '0002_reproductor'),
        ('fincas', '0001_initial'),
        ('reproduccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_alimentacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suministros_animales', to='catalogos.alimento')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones_animales', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alimentación animal',
                'verbose_name_plural': 'Alimentaciones animales',
                'ordering': ['-fecha_alimentacion'],
            },
        ),
        migrations.CreateModel(
            name='Lactancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lactancia', models.IntegerField(default=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_secado', models.DateField(blank=True, null=True)),
                ('dias_produccion', models.IntegerField(default=0)),
                ('total_litros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promedio_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ajuste_305_dias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SECADA', 'Secada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactancias', to='fincas.finca')),
                ('reproduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lactancias', to='reproduccion.reproduccion')),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactancias', to='animales.animal')),
            ],
            options={
                'verbose_name': 'Lactancia',
                'verbose_name_plural': 'Lactancias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionLeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('MANIANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=20)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_en_lactancia', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones_leche', to='fincas.finca')),
                ('lactancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones_leche', to='produccion.lactancia')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_leche_registradas', to=settings.AUTH_USER_MODEL)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones_leche', to='animales.animal')),
            ],
            options={
                'verbose_name': 'Producción de leche',
                'verbose_name_plural': 'Producciones de leche',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pesaje', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ganancia_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('condicion_corporal', models.DecimalField(decimal_places=2, default=0, help_text='Escala corporal, por ejemplo 1 a 5', max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_peso', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_peso', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_peso_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de peso',
                'verbose_name_plural': 'Registros de peso',
                'ordering': ['-fecha_pesaje'],
            },
        ),
    ]
