# Generated by Django 6.0.4 on 2026-04-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('nro_arete', models.CharField(max_length=100, unique=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad_ingreso_meses', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENDIDO', 'Vendido'), ('MUERTO', 'Muerto'), ('DESCARTE', 'Descarte'), ('MATADERO', 'Matadero')], default='ACTIVO', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animales/')),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_nacimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo_produccion', models.CharField(choices=[('CARNE', 'Carne'), ('LECHE', 'Leche'), ('DOBLE_PROPOSITO', 'Doble propósito')], default='DOBLE_PROPOSITO', max_length=30)),
                ('origen', models.CharField(choices=[('NACIDO_FINCA', 'Nacido en finca'), ('COMPRADO', 'Comprado'), ('DONADO', 'Donado')], default='NACIDO_FINCA', max_length=30)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.categoriaanimal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='fincas.finca')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_como_madre', to='animales.animal')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_como_padre', to='animales.animal')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(default='ACTIVA', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='parcelas/')),
                ('tamano', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacidad_maxima', models.IntegerField(default=0)),
                ('tipo_pastura', models.CharField(blank=True, max_length=100, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='fincas.finca')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_parcelas', to='animales.animal')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_animales', to='animales.parcela')),
            ],
        ),
    ]
