# Generated by Django 4.2.7 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('VENDIDO', 'Vendido'), ('MUERTO', 'Muerto'), ('DESCARTE', 'Descarte'), ('MATADERO', 'Matadero'), ('BAJA', 'Baja')], default='ACTIVO', max_length=30),
        ),
    ]
