# Generated by Django 6.0.4 on 2026-04-25 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_reproductor'),
        ('fincas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_compra', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('ALIMENTO', 'Alimento'), ('OTRO', 'Otro')], default='MEDICAMENTO', max_length=30)),
                ('fecha_compra', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_compra', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de compra',
                'verbose_name_plural': 'Notas de compra',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='catalogos.alimento')),
                ('nota_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_alimentos', to='compras.notacompra')),
            ],
            options={
                'verbose_name': 'Detalle compra alimento',
                'verbose_name_plural': 'Detalles compra alimentos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='catalogos.medicamento')),
                ('nota_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_medicamentos', to='compras.notacompra')),
            ],
            options={
                'verbose_name': 'Detalle compra medicamento',
                'verbose_name_plural': 'Detalles compra medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('ci', models.CharField(blank=True, max_length=30, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='notacompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='compras.proveedor'),
        ),
    ]
