# Generated by Django 6.0.4 on 2026-04-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('catalogos', '0002_reproductor'),
        ('fincas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoPrenez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_servicio', models.IntegerField(default=1)),
                ('fecha_probable_parto', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PRENADA', 'Preñada'), ('VACIA', 'Vacía'), ('REPETIR', 'Repetir servicio')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resultado_prenez', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('DUDOSO', 'Dudoso')], default='DUDOSO', max_length=30)),
                ('dias_gestacion', models.IntegerField(default=0)),
                ('metodo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_confirmacion', models.DateField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_eventos_reproductivos', to='fincas.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_eventos_reproductivos', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eventos_reproductivos_registrados', to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_prenez_reproduccion', to='catalogos.veterinario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InseminacionArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_servicio', models.IntegerField(default=1)),
                ('fecha_probable_parto', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PRENADA', 'Preñada'), ('VACIA', 'Vacía'), ('REPETIR', 'Repetir servicio')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_pajuela', models.CharField(blank=True, max_length=100, null=True)),
                ('lote_nitrogeno', models.CharField(blank=True, max_length=100, null=True)),
                ('tecnico_inseminador', models.CharField(blank=True, max_length=150, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_eventos_reproductivos', to='fincas.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_eventos_reproductivos', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eventos_reproductivos_registrados', to=settings.AUTH_USER_MODEL)),
                ('reproductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inseminaciones_artificiales', to='catalogos.reproductor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MontaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_servicio', models.IntegerField(default=1)),
                ('fecha_probable_parto', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PRENADA', 'Preñada'), ('VACIA', 'Vacía'), ('REPETIR', 'Repetir servicio')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('duracion_dias', models.IntegerField(default=1)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_eventos_reproductivos', to='fincas.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_eventos_reproductivos', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eventos_reproductivos_registrados', to=settings.AUTH_USER_MODEL)),
                ('reproductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montas_naturales_reproduccion', to='catalogos.reproductor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('fecha_parto_esperado', models.DateField(blank=True, null=True)),
                ('fecha_parto_real', models.DateField(blank=True, null=True)),
                ('tipo_parto', models.CharField(choices=[('NORMAL', 'Normal'), ('DISTOCICO', 'Distócico'), ('ABORTO', 'Aborto'), ('MULTIPLE', 'Múltiple')], default='NORMAL', max_length=30)),
                ('num_crias', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('SERVIDA', 'Servida'), ('PRENADA', 'Preñada'), ('PARIDA', 'Parida'), ('ABORTO', 'Aborto'), ('VACIA', 'Vacía')], default='SERVIDA', max_length=30)),
                ('peso_total_crias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('crias', models.ManyToManyField(blank=True, related_name='reproducciones_como_cria', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='fincas.finca')),
                ('inseminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproducciones_originadas', to='reproduccion.inseminacionartificial')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones_como_madre', to='animales.animal')),
                ('monta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproducciones_originadas', to='reproduccion.montanatural')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproducciones_como_padre', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproducciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
